export const DANG_NHAP = 'DANG_NHAP';
export const DANG_XUAT = 'DANG_XUAT';
export const LAY_ERRORS_DANG_NHAP = 'LAY_ERRORS_DANG_NHAP';
export const LAY_ERRORS_DANG_KY = 'LAY_ERRORS_DANG_KY';
export const RESET_ERRORS = 'RESET_ERRORS';
export const CREATE_COURSES = 'CREATE_COURSES';
export const CAP_NHAT_THONG_TIN = 'CAP_NHAT_THONG_TIN';
export const LAY_ERRORS_CAP_NHAT_THONG_TIN = 'LAY_ERRORS_CAP_NHAT_THONG_TIN';
export const KHOA_HOC_DA_GHI_DANH = 'KHOA_HOC_DA_GHI_DANH';
export const LAY_ERRORS_DA_GHI_DANH = 'LAY_ERRORS_DA_GHI_DANH';

